default: &default
  auth0_domain: <%= ENV.fetch("AUTH0_DOMAIN") { "dummy" } %>
  auth0_client_id: <%= ENV.fetch("AUTH0_CLIENT_ID") { "dummy" } %>
  auth0_client_secret: <%= ENV.fetch("AUTH0_CLIENT_SECRET") { "dummy" } %>

development:
  <<: *default

production:
  <<: *default
